### ISSUE TITLE
[마이페이지] 디자인 수정사항 반영

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#112]
## ❗ 이슈 요약

마이페이지 부분 디자인 수정사항 반영하겠습니다.

## 📝 todo

- [x] 마이페이지 프로필 이미지 삭제
- [x] 마이페이지 닉네임 밑에 커플 기념일 추가 (요일도)
- [x] 워딩 변경
- [x] 오픈소스 라이선스 추가
