### ISSUE TITLE
스플래쉬 & 온보딩 뷰 구현

### ISSUE THREAD

**Issue by haeti-dev** [U-is-Ni-in-Korea/Android-United#12]
## ❗ 이슈 요약

온보딩 뷰 구현

## 📝 todo

- [x] Splash Activity 구현
- [x] 온보딩 ViewPager2 구현
- [x] 버튼으로 화면 전환 구현
