### ISSUE TITLE
[타이머] QA

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#162]
## 📝 todo

- [x] 타이머 나갈때 startActivity 빼기
- [x] 버튼 xml 수정
- [ ] 타이머 생명주기 관리 (핸드폰 끄고 다시 켰을때 시간이 다 지난 상태면 오류남)
- [x] 핸드폰 뒤로가기 시 다이얼로그 띄우기
