### ISSUE TITLE
[히스토리] 메인 히스토리 뷰 구현

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#17]
## ❗ 이슈 요약
승부 히스토리 리스트가 나오는 뷰 구현

## 📝 todo

- [x] top app bar 구현
- [x] 리싸이클러 뷰 구현
- [x]  더미 데이터 넣기
- [x] 아이템 데코레이션으로 구분선 구현
- [x] empty view 그리기
- [x] empty view visible 처리
