### ISSUE TITLE
[QA] 한판승부 뷰 이슈

### ISSUE THREAD

**Issue by rkdmf1026** [U-is-Ni-in-Korea/Android-United#178]
## ❗ 이슈 요약

한판승부 디자인 부분 및 미적용 기능 추가

## 📝 todo

- [x] 미션 카테고리 공략팁 부분 줄바꿈 수정
- [x] 글자 수 초과 상태에서 미션 카테고리 선택 시, 메시지 출력
- [x] 미션 카테고리 선택하기 양 옆 dp및 제약 수정
- [ ] 한판승부 소원 작성하기 소원권 티켓 반응형으로 제약 걸기
- [x] 글자 수 초과 상태에서 뒤로가기 기능 추가
- [x] 진행중 공략팁 왼쪽정렬로 수정
