### ISSUE TITLE
[소원권]  소원권 뷰 구현

### ISSUE THREAD

**Issue by sub101** [U-is-Ni-in-Korea/Android-United#19]
## ❗ 이슈 요약
소원권 시작뷰를 구현할 예정입니다.

## 📝 todo
- [x] activity 내 textview 클릭시 fragment 변환 구현
- [x] cardview item 생성
- [x] multi-view type recyclerview 구현
- [x] ui 다듬기
- [x] recyclerview item 클릭시 화면 전환 기능
