### ISSUE TITLE
[한판승부] 한판승부 <-> 미션상세 전환 기능 구현

### ISSUE THREAD

**Issue by rkdmf1026** [U-is-Ni-in-Korea/Android-United#35]
## ❗ 이슈 요약

한판승부 <-> 미션상세 전환 기능 구현

## 📝 todo

- [ ] Send missionId From 한판승부 to 미션상세 
- [ ] Send missionId From 미션상세 to 한판승부
- [ ] MissionDetailCreateViewmodel 생성
- [ ] 나가기, 생성하기 다이얼로그 기능 구현
