### ISSUE TITLE
[온보딩] 닉네임 입력하기 서버통신 

### ISSUE THREAD

**Issue by haeti-dev** [U-is-Ni-in-Korea/Android-United#48]
## ❗ 이슈 요약

- 닉네임 서버통신 구현과 로직 구성

## 📝 todo

- [x] 10자리 넘어갔을 때 stroke 빨간색, helper text shown
- [x] 상태 up 일 때 버튼 enabled true
- [x] 다음 버튼 눌렀을 때 PATCH 통신
