### ISSUE TITLE
[마이페이지] 마이페이지 서버통신

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#53]
## ❗ 이슈 요약
마이페이지 서버통신 준비, 붙이기

## 📝 todo

- [x] 액티비티 뷰모델 사용해서 분리하기
- [x] 서버통신 작업 준비
- [x] 디자인 수정사항 반영
- [x] 서버통신
- [x] xml id 값 바꾸기
