### ISSUE TITLE
[한판승부] 한판승부기록 기능 구현

### ISSUE THREAD

**Issue by rkdmf1026** [U-is-Ni-in-Korea/Android-United#57]
## ❗ 이슈 요약
한판승부 기록 기능 구현

## 📝 todo
- [ ] 한판승부기록 viewmodel dto 수정
- [ ] 승부그만두기 다이얼로그 기능 구현
- [ ] 화면전환 기능 구현
