### ISSUE TITLE
[한판승부] API 연동 및 레파지토리 패턴 적용

### ISSUE THREAD

**Issue by rkdmf1026** [U-is-Ni-in-Korea/Android-United#61]
## ❗ 이슈 요약
[한판승부] API 연동 및 레파지토리 패턴 적용

## 📝 todo

- [ ] 한판승부생성 api 연동 및 레파지토리 패턴 적용, dto 수정
- [ ] 한판승부기록 api 연동 및 레파지토리 패턴 적용
- [ ] 한판승부결과 api 연동 및 레파지토리 패턴 적용
