### ISSUE TITLE
[전체] QA 준비

### ISSUE THREAD

**Issue by haeti-dev** [U-is-Ni-in-Korea/Android-United#65]
## ❗ 이슈 요약

QA 준비사항들 리스트업

## 📝 todo

- [x] 닉네임 공백 로직 (준희)
- [x] 자동 로그인
- [x] 초대코드 입력하기에서 홈으로 넘어갈 때 EditText box 깜빡이 (준희)
- [x] 디데이 숫자
- [ ] <한판 승부> 깜빡이
- [x] <전체> 뒤로가기 버튼 눌렀을 때 앱 꺼지는 거 막기 (준희)
- [x] <전체> 커서, 하이라이트 색상 수정 (준희)
- [x] <초대코드공유> 에서 상대연결확인이 통과 되었음에도 상대와 연결되지 않았어요 토스트가 뜸
- [x] <전체> PNG 해상도 분리
- [ ] <전체> 앱 강제 종료 막기
- [ ] <홈> 스코어 보드 구분선 그림자
