### ISSUE TITLE
[홈] 한판승부로 넘어가는 분기 처리

### ISSUE THREAD

**Issue by haeti-dev** [U-is-Ni-in-Korea/Android-United#72]
## ❗ 이슈 요약

한판승부로 넘어갈 때 로직

## 📝 todo

- [x] 홈 조회에서 shortgame 의 enabled 가 false 면 생성으로 보내기
- [x] true 면 roundGameId를 보내서 shortGame GET 통신
- [x] 통신해서 받은 값 중 result 가 UNDIRECTED 면 기록하기로
- [x] UNDIRECTED 가 아니면 상대 승부 기다리기로
