### ISSUE TITLE
[한판승부] 한판승부생성 세부기능 수정

### ISSUE THREAD

**Issue by rkdmf1026** [U-is-Ni-in-Korea/Android-United#74]
## ❗ 이슈 요약
한판승부생성 소원권 작성 세부기능 수정 및 스테이터스바 색상 적용, 툴바 적용

## 📝 todo

- [ ] 글자 수 초과시 버튼 처리
- [ ] 스테이터스바 색상 적용
- [ ] 툴바로 타이틀 고정
