### ISSUE TITLE
[소원권] 분담

### ISSUE THREAD

**Issue by sub101** [U-is-Ni-in-Korea/Android-United#84]
## ❗ 이슈 요약
소원권 마무리 하겠습니다.

## 📝 todo

- [ ] 소원권 생성 patch
- [ ] 소원권 사용하기 patch
- [ ] 소원권 전체 조회하기 - 새소원권 개수 첫 화면 null값 이슈
- [ ] 소원권 전체 조회하기 -소원권 상대 소원권 페이지 전체 조회
- [ ] 소원권 전체 조회하기 -소원권 사용여부에 따른 화면 전환
- [ ] 소원권 전체 조회하기 -이미지 api 연결
- [ ] 소원권 상세 조회하기 - 아이디는 넘어오는데 값호출이 null값 이슈
