### ISSUE TITLE
[히스토리] 히스토리 뷰 리팩토링

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#91]
## ❗ 이슈 요약
히스토리 부분 리팩토링 하겠슴다

## 📝 todo

- [x] 네이밍 수정 
- [x] 로딩뷰 넣기
- [x] 깜빡거리는 현상 해결
- [x] 패턴 잘 적용되었는지 점검
- [x] 불필요한 리소스 삭제
