### ISSUE TITLE
[타이머] 타이머 구현하기

### ISSUE THREAD

**Issue by l2zh** [U-is-Ni-in-Korea/Android-United#99]
## ❗ 이슈 요약

타이머를 만들어봅시다

## 📝 todo

- [x] 뷰 그리기
- [x] 타이머 기능 구현
- [x] 백그라운드에서도 살아있게 하기
- [x] 프로그래스 바 시간에 맞춰서 연동
- [x] 소리,진동 구현 (진동 구현 O)
- [x] 다른 액티비티로 전환 후 다시 돌아왔을 때 살아있게 하기 (workmanager 사용)
- [x] 타이머 삭제 구현
- [x] 타이머 종료시 프래그먼트 전환 후 스낵바
- [x] 타이머 일시정지, 다시시작 구현
